version: "3"

services:
  redis:
    container_name: gifty-redis-dev
    build:
      dockerfile: Dockerfile
      context: ./config/redis/dev
    image: limhwasup/gifty-redis-dev
    ports:
      - "6379:6379"

  backend-dev:
    container_name: backend-dev
    image: limhwasup/gifty-server-dev
    build:
      dockerfile: Dockerfile
      context: .
    hostname: backend-dev
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: always

  nginx:
    container_name: gifty-nginx-dev
    image: limhwasup/gifty-nginx-dev
    build:
      dockerfile: Dockerfile
      context: ./config/nginx/dev
    depends_on:
      - backend-dev
    ports:
      - "80:80"
      - "443:443" # Add port for HTTPS
    volumes:
      - ./config/nginx/dev/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro # Share SSL certification
    restart: always

#  fastapi:
#    container_name: fastapi-dev
#    build:
#      dockerfile: Dockerfile
#      context: ./config/fastapi/dev
#    ports:
#      - "8000:8000"

