version: "3"

services:
  redis:
    container_name: gifty-redis-prod
    build:
      dockerfile: Dockerfile
      context: ./config/redis/prod
    image: limhwasup/gifty-redis-prod
    ports:
      - "6379:6379"

  backend-prod:
    container_name: backend-prod
    image: limhwasup/gifty-server-prod
    build:
      dockerfile: Dockerfile.prod
      context: .
    hostname: backend-prod
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: always

  nginx:
    container_name: gifty-nginx-prod
    image: limhwasup/gifty-nginx-prod
    build:
      dockerfile: Dockerfile
      context: ./config/nginx/prod
    depends_on:
      - backend-prod
    ports:
      - "80:80"
      - "443:443" # Add port for HTTPS
    volumes:
      - ./config/nginx/prod/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro # Share SSL certification
    restart: always

#  fastapi:
#    container_name: fastapi-dev
#    build:
#      dockerfile: Dockerfile
#      context: ./config/fastapi/dev
#    ports:
#      - "8000:8000"

